### ISSUE TITLE
:zap: compress your background image and use cdn

### ISSUE THREAD

**Issue by YunYouJun** [MleMoe/blog#1]
Hey, MIA. Your background image is so big and slow to load, which is very inelegant.

I compressed it for you and provided a link (use my national CDN) for you to use.
It has nationwide nodes to ensure extremely fast access speeds anywhere in the country.

When the browser supports `webp`, it can become a smaller `webp`.

`https://upyun.yunyoujun.cn/images/polar-bear-and-girl.jpg`

![](https://upyun.yunyoujun.cn/images/polar-bear-and-girl.jpg)

If you give me the permission of a maintainer, I can create a PR for you.

And you just need to say thank you.

**Comment by MleMoe** [comment]
Thanks!

**Comment by MleMoe** [comment]
Thanks!
