### ISSUE TITLE
前端工程化

### ISSUE THREAD

**Issue by Flynn-Lu** [MleMoe/blog#3]
想问下博主校招对工程化要求怎么样呢 有没有什么好的学习途径？现阶段比较没思路 感觉又多又杂 不知道学到什么才够

**Comment by MleMoe** [comment]
正常来说，校招对工程化的要求不高。只要知道基础思想就行了。例如：

- gulp/grunt 做任务管理
- webpack/rollup 打包
- babel 转译工具（知道原理是使用 AST 就行）
- vite no-bundle 开发服务器 & 构建流程

还有一些 esbuild、SWC 这些，工程化的东西了解一下就行。前端校招主要是看基础，计算机基础和前端基础。

**Comment by Flynn-Lu** [comment]
好的 还想问下前端基础包括node和ts或是echarts这种吗？ 看到很多大厂要求里提到 不知道是不是这些也都要掌握的比较好呢

**Comment by MleMoe** [comment]
ts 和 node 是需要的，目前基本开发都是用 ts，可以了解一下类型编程，node 起码知道事件循环，不会要求你都会。echarts 没必要，日常工作不会用到数据可视化哈
